name: app_prueba
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  firebase_storage: ^10.2.3
  provider: ^6.0.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
